project:
  type: website
  output-dir: docs
  
editor: source

website:  
  # options: https://quarto.org/docs/reference/projects/websites.html
  # title: "Owen Choy"
  navbar:
    pinned: true
    logo: logos/owen choy logos/owen choy red rounded.png
    left:
      - href: index.qmd
        text: About Me
      - education.qmd
      - portfolio.qmd
      # - photos.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/owen-choy/
      - icon: github
        href: https://github.com/owenchoy
      - icon: envelope
        href: mailto:owenchoy02@gmail.com
  google-analytics:
    tracking-id: "G-M1TLPMSPTR"
    # storage: none
        
  page-footer:
    background: dark
    left: |
      Owen Choy
      <br>
      Last Updated: June 2024
    right: Built with [Quarto](https://quarto.org/){target=_blank}
    
  favicon: logos/owen choy logos/owen choy red rounded.png
  # sidebar: # https://quarto.org/docs/reference/projects/websites.html#sidebar
    # style: docked
    
  search: 
    location: navbar
    type: textbox
    
  #creates a preview when the link is pasted: https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true 
  
format:
  html:
    theme: 
      - styles.scss 
    mainfont: Sarabun
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px # slightly wider body than default
      margin-width: 250px
      gutter-width: 1rem
    # reference-location: margin
    # page-layout: full
    

